"""In-memory lookup of German municipalities (Gemeinden) with coordinates.

The dataset is shipped as a CSV file next to the application code and is
generated by ``scripts/places/extract_places.py`` from the quarterly
"Gemeindeverzeichnis" published by the Statistisches Bundesamt (Destatis).
"""

import csv
import logging
import unicodedata
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_PLACES_CSV = Path(__file__).resolve().parent.parent / "resources" / "places.csv"

# Umlauts and the sharp s have well established transliterations that users
# frequently type instead of the actual character (e.g. "Muenchen").
_TRANSLITERATIONS = {
    "ä": "ae",
    "ö": "oe",
    "ü": "ue",
    "ß": "ss",
}


def normalize(text: str) -> str:
    """Normalize text for accent and case insensitive matching."""
    lowered = text.casefold().strip()
    transliterated = "".join(_TRANSLITERATIONS.get(char, char) for char in lowered)
    decomposed = unicodedata.normalize("NFKD", transliterated)
    return "".join(char for char in decomposed if not unicodedata.combining(char))


@dataclass(frozen=True)
class Place:
    """A German municipality with its geographic centre coordinates."""

    ars: str
    name: str
    designation: str
    postal_code: str
    district: str
    state: str
    lat: float
    lng: float
    population: int

    @property
    def label(self) -> str:
        """Human readable, disambiguated label, e.g. "Aach (54298, Trier-Saarburg)"."""
        details = [self.postal_code] if self.postal_code else []
        if self.district and self.district != self.name:
            details.append(self.district)
        return f"{self.name} ({', '.join(details)})" if details else self.name


class PlaceClient:
    """Loads the place dataset once and answers autocomplete queries from memory."""

    def __init__(self, csv_path: Path | None = None):
        self._csv_path = Path(csv_path) if csv_path else DEFAULT_PLACES_CSV
        self._places: list[Place] = []
        self._normalized_names: list[str] = []
        self._by_id: dict[str, Place] = {}
        self._load()

    def _load(self) -> None:
        if not self._csv_path.exists():
            logger.error("Place dataset not found at %s", self._csv_path)
            return

        places: list[Place] = []
        with self._csv_path.open(encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                try:
                    places.append(
                        Place(
                            ars=row["ars"],
                            name=row["name"],
                            designation=row.get("designation", ""),
                            postal_code=row.get("postal_code", ""),
                            district=row.get("district", ""),
                            state=row.get("state", ""),
                            lat=float(row["lat"]),
                            lng=float(row["lng"]),
                            population=int(row.get("population") or 0),
                        )
                    )
                except (KeyError, TypeError, ValueError):
                    logger.warning("Skipping malformed place row: %s", row)

        # Larger municipalities are the more likely match for a short query,
        # so pre-sort by population to keep the search itself cheap.
        places.sort(key=lambda place: (-place.population, place.name))

        self._places = places
        self._normalized_names = [normalize(place.name) for place in places]
        self._by_id = {place.ars: place for place in places}
        logger.info("Loaded %d places from %s", len(places), self._csv_path)

    @property
    def count(self) -> int:
        return len(self._places)

    def get(self, ars: str) -> Place | None:
        """Look up a single place by its official regional key (ARS)."""
        return self._by_id.get(ars)

    def search(self, query: str, limit: int = 10) -> list[Place]:
        """Find places whose name or postal code matches ``query``.

        Prefix matches rank before substring matches, and within each group the
        more populous municipality wins.
        """
        normalized_query = normalize(query)
        if not normalized_query:
            return []

        prefix_matches: list[Place] = []
        substring_matches: list[Place] = []
        postal_matches: list[Place] = []
        is_postal_query = normalized_query.isdigit()

        for place, normalized_name in zip(self._places, self._normalized_names):
            if is_postal_query:
                if place.postal_code.startswith(normalized_query):
                    postal_matches.append(place)
            elif normalized_name.startswith(normalized_query):
                prefix_matches.append(place)
            elif normalized_query in normalized_name:
                substring_matches.append(place)

            if len(prefix_matches) >= limit or len(postal_matches) >= limit:
                break

        return (prefix_matches + postal_matches + substring_matches)[:limit]
