services:
  envoy:
    image: envoyproxy/envoy:v1.36-latest
    ports:
      - "9090:8080"
      - "9902:9901" # Admin interface
    volumes:
      - ./config/out/app/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./config/out/app/envoy-token-secret.yaml:/etc/envoy/token-secret.yaml:ro
      - ./config/out/app/envoy-hmac-secret.yaml:/etc/envoy/hmac-secret.yaml:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    build:
      context: . # Use the root context to access python packages stored in /lib
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    env_file:
      - ./backend/.env
    environment:
      - DATA_PATH=/app/data
      - BACKUP_PATH=/app/backups
      - PYTHONPATH=/app
      - DOCKER_BUILDKIT=1
      - BUILDKIT_PROGRESS=plain
      - ENVIRONMENT=development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - DOCKER_BUILDKIT=1
      - BUILDKIT_PROGRESS=plain
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
    driver: local

networks:
  default:
    name: app
